name: Attach compact_tree.h to release
on:
  release:
    types: [published]
jobs:
  attach_py:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Upload compact_tree.h to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: CompactTree/compact_tree.h
          asset_name: compact_tree.h
          tag: ${{ github.ref }}
          overwrite: true
